artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Industrial_and_Scientific_5.json.gz
  local_data_file_path: artifacts/data_ingestion/data.gz
  unzip_directory: artifacts/data_ingestion

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_ingestion/data.json

build_model:
  root_dir: artifacts/build_model
  model_path: artifacts/build_model/base_model.h5

train_model:
  root_dir: artifacts/train_model
  trained_model_path: artifacts/train_model/trained_model.h5

evaluate_model:
  root_dir: artifacts/evaluate_model